---
title: "Untitled"
author: "Jueyan Lin"
date: "December 5, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(glmnet)
library(readxl)
library(earth)
```

```{r}
store=list()
for (i in 2:9) {
  store[[i]] = read_excel(paste0("Store",i,"-1.xlsx"))
}

```

```{r}
rmse_matrix = c()
avg_rmse = c()
for (s in 2:9) {
  ifTrain = store[[s]]["Random"]=="Train"
  rmse_list = c()
  for (i in 1:24) {
    
    traindata = store[[s]][ifTrain,c(3:98,98+i)]
    # make Yi be Y (e.g. column Y1 is now named Y)
    colnames(traindata) = c(colnames(traindata)[1:96],"Y")
    # test data without Y to be used for prediction
    testdata = store[[s]][!ifTrain,3:98]
    rownames(testdata) = 1:nrow(testdata)
    testdata
    # Y of test data
    test_y = as.matrix(store[[s]][!ifTrain,98+i])
    rownames(test_y) = 1:nrow(test_y)
    test_y
    
    f_quant = summary(traindata[97])[2]
    s_quant = summary(traindata[97])[3]
    t_quant = summary(traindata[97])[5]

    for (z in 1:nrow(traindata)) {
      if (traindata[z,"Y"] <= f_quant) {
        traindata[z,'S'] = 1
      }
      if (traindata[z,"Y"] <= s_quant) {
        traindata[z,'S'] = 2
      }
      if (traindata[z,"Y"] <= t_quant) {
        traindata[z,'S'] = 3
      }
      else {
        traindata[z,'S'] = 4
      }
    }
    
    for (z in 1:nrow(testdata)) {
      if (test_y[z] <= f_quant) {
        testdata[z,'S'] = 1
      }
      if (test_y[z] <= s_quant) {
        testdata[z,'S'] = 2
      }
      if (test_y[z] <= t_quant) {
        testdata[z,'S'] = 3
      }
      else {
        testdata[z,'S'] = 4
      }
    }
    
    traindata['Y'] = log(traindata['Y'])
    for (j in 1:24) {
      traindata[paste0("P",j)] = log(traindata[paste0("P",j)])
      testdata[paste0("P",j)] = log(testdata[paste0("P",j)])
    }
    
    ## paste your model and prediction ##
    test_y = as.matrix(store[[s]][!ifTrain,98+i])
    x_train = as.matrix(traindata)
    x_test = as.matrix(testdata)
    
    ridge_mod = glmnet(x_train[,c(1:96,98)],traindata$Y,alpha = 1)
    cv.out_r=cv.glmnet(x_train[,c(1:96,98)],traindata$Y,alpha = 1)
    plot(cv.out_r)
    bestlam_r=cv.out_r$lambda.min
    ridge_pred=predict(ridge_mod,s=bestlam_r,x_test)
    
    pred_o = exp(ridge_pred)
    #test_yo = as.matrix(store[[s]][!ifTrain,98+i])
    rmse =sqrt(mean((pred_o-test_y)^2))
    ## -------------------------------- ##
    #print(rmse)
    # store each rmse in a list
    rmse_list[i] = rmse
    #print(rmse)
  }
  # store each store rmse into a matrix
  rmse_matrix = cbind(rmse_matrix,rmse_list)

  # print(mean(rmse_list))
  avg_rmse[s-1] = mean(rmse_list)
}
print(avg_rmse)
# write the rmse of each item in each store into a csv file
#write.csv(rmse_matrix,file = "store_mars_time.csv")
```
